### ISSUE TITLE
No files collected and no output from mehrai.py

### ISSUE THREAD

**Issue by ch40s** [compoterhacker/mehrai#3]
I checked the history of commands on the honeypot and confirmed that it has been already infected by mirai, however no files have been collected and there is no output from mehrai.py.

I don't know if that fact that I removed "/rootfs" from mehrai.py could be related, however I don't have /rootfs under the dockerid directory.

**Comment by compoterhacker** [comment]
I just pushed a new version that might help. Otherwise, I'm not sure why it wouldn't work. What distro and version of docker are you running? What version of python?

**Comment by ch40s** [comment]
I used the latest version of mehrai.

Debian 8
Docker version 1.12.3, build 6b644ec
Python 2.7.9

**Comment by ch40s** [comment]
Problem solved by using the correct path. 
The command "docker ps -l --no-trunc | grep 'mehrai' | awk '{print $1}'" doesn't show the correct id.

**Comment by compoterhacker** [comment]
If you have multiple builds with the same name, sure. Grep for your current tag then, or just grab it from the command line and copy pasta.
