### ISSUE TITLE
Netlink question

### ISSUE THREAD

**Issue by VPaulV** [compoterhacker/mehrai#5]
Hi,

Do you know if some special kernel configuration is required to make use of this netlink approach?
I have tried to run this honeypot on Kali, but cannot catch any event. (processing simply stack on sock_data = self.sock.recv()

I know that you "AIN'T DOIN SHIT", but probably you could give an advice =)
```
uname -a
SMP Debian 4.5.3-2kali1 (2016-05-09) x86_64 GNU/Linux
```

**Comment by VPaulV** [comment]
UPD: found the problem. Was something wrong in toggle_mcast(). Have changed it to ugly hardcode and it started to work

```
        data = struct.pack("=IHHII IIIIHH I", 16 + 20 + 4, 3, 0, 0, os.getpid(), 1, 1, 0, 0, 4, 0, 1)
        self.sock.send(data)
```

**Comment by compoterhacker** [comment]
I was being a bit factious with that advice line ;) 

I noticed a similar problem on a debian box(forget what kernel it was), and didn't bother looking into it, but I will now. Thanks for the update! I'll see if I can put something together to address different kernels and not have to be so hacky. Next commit will be a much more fully-realized honeypot and I'll be sure to address this.
